@startuml
AwFDListener <|-- AwFDConnector
AwFD <|-- AwSocket
AwFD --* AwProcess
AwFD o-- AwFDListener
AwPoll <|-- AwEventLoop
AwEventLoop <|-- AwApp
AwPoll o-- AwFD

class AwApp {
 -args : std::vector<const char *>
 +getArgs()
 +getOptionValue( ... )
}

class AwEventLoop {
}

class AwFDListener {
 +onReadable()
 +onWritable()
}

class AwFD {
 -listeners : std::vector<AwFDListener *>
 #fd : int
 +write()
 +read()
 +addListener()
 +notify()
}

class AwProcess {
 #fd_stdin : AwFD
 #fd_stdout : AwFD
 #fd_stderr : AwFD
 +write()
 +read()
 +readErr()
}
@enduml
