@startuml
AwFDListener <|-- AwFDConnector
AwFD <|-- AwSocket
AwFD --* AwProcess
AwFD o-- AwFDListener

class AwFDListener {
 +onReadable()
 +onWritable()
}

class AwFD {
 -listeners : std::vector<AwFDListener *>
 #fd : int
 +write()
 +read()
 +addListener()
 +notify()
}

class AwProcess {
 #fd_stdin : AwFD
 #fd_stdout : AwFD
 #fd_stderr : AwFD
 +write()
 +read()
 +readErr()
}
@enduml
