@startuml
start
repeat
:Waiting for a connection;
split
:Terminate<
stop
split again
:Connection<
:accept();
 fork
   :Initialise session;
   :Run session;
   :Clean up;
   end
 fork again
 end fork
end split
repeat while()
@enduml
